spring:
  application:
    name: departamentos-api
  datasource:
    url: jdbc:postgresql://localhost:5432/departamentos
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${SERVER_PORT:8080}
